/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemafinanceiro.view;

/**
 *
 * @author Junior
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        imDespesas = new javax.swing.JMenuItem();
        imGrupoFinanceiro = new javax.swing.JMenuItem();
        imStatus = new javax.swing.JMenuItem();
        imExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Financeiro");
        setPreferredSize(new java.awt.Dimension(900, 700));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        imDespesas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        imDespesas.setMnemonic('o');
        imDespesas.setText("Despesas");
        imDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imDespesasActionPerformed(evt);
            }
        });
        fileMenu.add(imDespesas);

        imGrupoFinanceiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        imGrupoFinanceiro.setMnemonic('x');
        imGrupoFinanceiro.setText("Grupo Financeiro");
        imGrupoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imGrupoFinanceiroActionPerformed(evt);
            }
        });
        fileMenu.add(imGrupoFinanceiro);

        imStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        imStatus.setText("Status");
        imStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imStatusActionPerformed(evt);
            }
        });
        fileMenu.add(imStatus);

        imExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        imExit.setText("Sair");
        imExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imExitActionPerformed(evt);
            }
        });
        fileMenu.add(imExit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imGrupoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imGrupoFinanceiroActionPerformed
        GrupoFinanceiroView gpv = new GrupoFinanceiroView();
        gpv.setVisible(true);
        this.desktopPane.add(gpv);
    }//GEN-LAST:event_imGrupoFinanceiroActionPerformed

    private void imDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imDespesasActionPerformed
        DespesasView dv = new DespesasView();
        dv.setVisible(true);
        this.desktopPane.add(dv);
    }//GEN-LAST:event_imDespesasActionPerformed

    private void imExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_imExitActionPerformed

    private void imStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imStatusActionPerformed
     StatusView sv = new StatusView();
     sv.setVisible(true);
     this.desktopPane.add(sv);
    }//GEN-LAST:event_imStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem imDespesas;
    private javax.swing.JMenuItem imExit;
    private javax.swing.JMenuItem imGrupoFinanceiro;
    private javax.swing.JMenuItem imStatus;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
